services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "${PORT}:25565"
    environment:
      EULA: "TRUE"
      TYPE: FABRIC
    dns:
      - 8.8.8.8
    env_file:
      - .env
    volumes:
      - ./data:/data
